return {
	Class = "∴",
	Constant = "𝜋",
	Constructor = "⬡",
	Enum = "",
	EnumMember = "",
	Event = "",
	Field = "→",
	File = "",
	Folder = "",
	Function = "ƒ",
	-- Function = 'λ',
	Interface = "",
	Keyword = "🗝",
	Method = "𝘮",
	Module = "[<>]",
	Operator = "≠",
	Property = "∷",
	Reference = "⊷",
	Snippet = "{}",
	Struct = "",
	Text = "#",
	TypeParameter = "×",
	Unit = "()",
	Variable = "𝓧",
}
